In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\Dell\\Downloads\\datasets\\survey_lung_cancer.csv")
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [8]:
columns_to_drop=['GENDER','AGE','WHEEZING','PEER_PRESSURE','CHRONIC DISEASE','FATIGUE ','COUGHING','SHORTNESS OF BREATH','SWALLOWING DIFFICULTY','ALLERGY ']
df=df.drop(columns=columns_to_drop)

In [10]:
columns_to_drop=['YELLOW_FINGERS','ANXIETY','CHEST PAIN']
df=df.drop(columns=columns_to_drop)

In [11]:
df.head()

   SMOKING  ALCOHOL CONSUMING LUNG_CANCER
0        1                  2         YES
1        2                  1         YES
2        1                  1          NO
3        2                  2          NO
4        1                  1          NO